[package]
name = "btree"
version = "0.1.0"
authors = ["William Speirs <bill.speirs@gmail.com>"]

[dependencies]
rand = "*"
bincode = "^1.0.0-alpha4"
serde = "^0.9"
serde_derive = "^0.9"
itertools = "^0.5.9"
